spring:
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: ddemys
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
